steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/platy-api', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/platy-api']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'platy-api', '--image', 'gcr.io/$PROJECT_ID/platy-api', '--region', 'us-central1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/platy-api
